### ISSUE TITLE
Allow smmoth update

### ISSUE THREAD

**Issue by cornelinux** [cornelinux/yubikey-luks#39]
With the change of the keyscript, we need to be able to run a smooth update on debian/ubuntu.
Otherwise updating to a newer version, will result in LUKS not being accessable with the yubikey.

We need to parse /etc/crypttab for the occurrance of ``luks`` and add the keyscript.

    luks,keyscript=/usr/share/yubikey-luks/ykluks-keyscript

**Comment by Vincent43** [comment]
Actually it's broken right now if users updated their Ubuntu and Debian systems to latest versions so users have to fix something themselves anyway.

I'm afraid that unconditionally modifying `/etc/crypttab` in post install script may be seen as too aggressive behavior as this is rather considered as local configuration file. There is possibility that user explicitly removed `keyscript` from i.e. they don't want to use yubikey-luks anymore.

Broken systems can be fixed by using cmdline approach. I agree that we can advertise this situation more in manpage/docs and yubikey-luks-enroll.

**Comment by cornelinux** [comment]
You are right.
I am running Ubuntu 16.04 (still) and if I would upgrade from yubikey-luks 0.5.1 to 0.6 with the changed keyscript functionality YK in LUKS would not work anymore. Currently it does.
So I need/want to put a bit thoughts about how to smooth the update...

**Comment by Vincent43** [comment]
Maybe create separate branches for 0.5.x (legacy) and 0.6 (current)?

You may crates 0.5.x branch, reset it to https://github.com/cornelinux/yubikey-luks/commit/3752b8077218cde74e0d1b34baa4a06efaf9e53c and only backport fixes which aren't breaking backward compatibility.

In example: https://github.com/cornelinux/yubikey-luks/commit/94642f70f7f38f8ac22f68a102ff0bca8a372bf8 would be good to backport but https://github.com/cornelinux/yubikey-luks/pull/40 perhaps not.

**Comment by cornelinux** [comment]
To my understanding this was only a problem from 16.04 to 18.04.
So I am closing this. (After all it is my issue ;-)
